export const projects = [
  {
    name: "Jogos de Azar",
    img: "https://i.imgur.com/ZJzzmFl.png",
    desc: "Projeto realizado no primeiro módulo da Kenzie Academy Brasil, onde podemos por em prática todos os conhecimentos aprendidos de HTML, CSS e JavaScript. Foram feitos dois jogos de azar, um caça niquel e um caça palavras com o objetivo de treinar os conhecimentos.",
    git: "https://github.com/nicollasanderson/ksociety-jogos-de-azar",
    demo: "https://nicollasanderson.github.io/ksociety-jogos-de-azar/",
    stack: "Front-end",
    used: [
      "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original-wordmark.svg",
      "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original-wordmark.svg",
      "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg",
    ],
  },
  {
    name: "Torre de Hanoi",
    img: "https://i.imgur.com/QYhpkg5.png",
    desc: "A torre de Hanoi é um jogo de encaixe com 3 níveis de dificuldade, foi construído utilizando HTML, CSS e Javascript.",
    git: "https://github.com/nicollasanderson/Torre-de-Hanoi",
    demo: "https://nicollasanderson.github.io/Torre-de-Hanoi/",
    stack: "Front-end",
    used: [
      "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original-wordmark.svg",
      "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original-wordmark.svg",
      "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg",
    ],
  },
  {
    name: "Nu Kenzie",
    img: "https://i.imgur.com/01C6bQX.png",
    desc: "Projeto com o objetivo de fazer o calculo das finaças pessoais, marcando entrada e saida de valores, além do valor total de todas as despesas. Projeto feito em React, Html, Css e JavaScript.",
    git: "https://github.com/nicollasanderson/Nu-Kenzie",
    demo: "https://nukenzie-nicollasanderson.vercel.app/",
    stack: "Front-end",
    used: [
      "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original-wordmark.svg",
      "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original-wordmark.svg",
      "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg",
      "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original-wordmark.svg",
    ],
  },
  {
    name: "Kenzie Hub",
    img: "https://i.imgur.com/rWy7AVD.png",
    desc: "Projeto com o objetivo de armazenar as linguagens aprendidas e a proficiência em cada uma delas. Feito em React, Html, Css e JavaScript. User: teste-top@teste.com Senha: 123456",
    git: "https://github.com/nicollasanderson/Kenzie-Hub",
    demo: "https://react-entrega-s2-kenzie-hub-nicollasanderson-nv7llcgr0.vercel.app/",
    stack: "Front-end",
    used: [
      "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original-wordmark.svg",
      "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original-wordmark.svg",
      "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg",
      "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original-wordmark.svg",
    ],
  },
  {
    name: "Burguer Kenzie",
    img: "https://i.imgur.com/GwDPeQJ.png",
    desc: "A Burguer Kenzie é uma pequena hamburgueria virtual feita em React, Html, Css e JavaScript.",
    git: "https://github.com/nicollasanderson/Burguer-Kenzie",
    demo: "https://react-entrega-s1-hamburgueria-da-kenzie-nicollasanderson.vercel.app/",
    stack: "Front-end",
    used: [
      "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original-wordmark.svg",
      "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original-wordmark.svg",
      "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg",
      "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original-wordmark.svg",
    ],
  },
  {
    name: "G4mes Hub",
    img: "https://i.imgur.com/wBett4k.png",
    desc: "O G4mes Hub é uma plataforma de interação entre jogadores de todo o mundo. Aqui, você pode deixar sua opinião sobre diversos jogos, além de deixar seu link e uma pontuação. Projeto feito no final do 3° módulo de React.",
    git: "https://github.com/victor-sagulo/capstone-m3-projeto-final",
    demo: "https://capstone-m3-projeto-final.vercel.app/",
    stack: "Front-end",
    role: "Product Owner",
    used: [
      "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/html5/html5-original-wordmark.svg",
      "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/css3/css3-original-wordmark.svg",
      "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/javascript/javascript-original.svg",
      "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/react/react-original-wordmark.svg",
    ],
  },
  {
    name: "Music Club Shop API",
    img: "https://i.imgur.com/gKNHmfF.png",
    desc: "API Restful feita com o objetivo de gerenciar uma loja de instrumentos e materiais musicais. Usuários podem se cadastrar, adicionar produtos ao carrinho e enviar para o endereço desejado. Projeto feito com Node.js, Typescript e Postgresql para o capstone do 4° módulo da Kenzie Academy Brasil.",
    git: "https://github.com/nicollasanderson/music-club-shop-api",
    demo: "https://api-music-club-shop.herokuapp.com/",
    stack: "Back-end",
    role: "Tech Lead",
    used: [
      "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/nodejs/nodejs-original.svg",
    ],
  },
  {
    name: "Empresa Python",
    img: "https://t3.ftcdn.net/jpg/01/16/75/94/360_F_116759427_l4AGnmouXXUnW4YGKHJrmYHoMrBpjh0L.jpg",
    desc: "Sistema simples de gerenciamento de uma empresa, onde é possível criar uma empresa, funcionários e genrentes e associar elas entre si, além de salvar a empresa em um arquivo json. Projeto feito com o objetivo de aprender as bases de Python para realizar a criação de API's Restful.",
    git: "https://github.com/nicollasanderson/Empresa-Python",
    demo: "#",
    stack: "Back-end",
    used: [
      "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original-wordmark.svg",
    ],
  },
  {
    name: "Kenzie Pet",
    img: "https://t3.ftcdn.net/jpg/01/16/75/94/360_F_116759427_l4AGnmouXXUnW4YGKHJrmYHoMrBpjh0L.jpg",
    desc: "API Restful simples para cadastrar animais, suas espécies e características. Projeto feito com Python, Django e Rest Framework.",
    git: "https://github.com/nicollasanderson/Kenzie-Pet",
    demo: "#",
    stack: "Back-end",
    used: [
      "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/python/python-original-wordmark.svg",
      "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/django/django-plain-wordmark.svg",
    ],
  },
];
