export const projects = [
  {
    name: "Jogos de Azar",
    img: "https://i.imgur.com/ZJzzmFl.png",
    desc: "Projeto em grupo realizado no primeiro módulo da Kenzie Academy Brasil, onde podemos por em prática todos os conhecimentos aprendidos de HTML, CSS e JavaScript. Foram feitos dois jogos de azar, um caça niquel e um caça palavras com o objetivo de treinar os conhecimentos",
    git: "https://github.com/nicollasanderson/ksociety-jogos-de-azar",
    demo: "https://nicollasanderson.github.io/ksociety-jogos-de-azar/",
    stack: "Front-end",
  },
  {
    name: "Torre de Hanoi",
    img: "https://i.imgur.com/QYhpkg5.png",
    desc: "Projeto realizado em dupla onde reproduzimos o jogo Torre de Hanoi com 3 níveis de dificuldade e verificações de vitória, utilizando apenas HTML, CSS e JavaScript.",
    git: "https://github.com/nicollasanderson/Torre-de-Hanoi",
    demo: "https://nicollasanderson.github.io/Torre-de-Hanoi/",
    stack: "Front-end",
  },
  {
    name: "Nu Kenzie",
    img: "https://i.imgur.com/01C6bQX.png",
    desc: "Projeto com o objetivo de fazer o calculo das finaças pessoais, marcando entrada e saida de valores, além do valor total de todas as despesas. Projeto feito em React, Html, Css e JavaScript.",
    git: "https://github.com/nicollasanderson/Nu-Kenzie",
    demo: "https://nukenzie-nicollasanderson.vercel.app/",
    stack: "Front-end",
  },
  {
    name: "Kenzie Hub",
    img: "https://i.imgur.com/rWy7AVD.png",
    desc: "Projeto com o objetivo de armazenar as linguagens aprendidas e a proficiência em cada uma delas. Feito em React, Html, Css e JavaScript.",
    git: "https://github.com/nicollasanderson/Kenzie-Hub",
    demo: "https://react-entrega-s2-kenzie-hub-nicollasanderson-nv7llcgr0.vercel.app/",
    stack: "Front-end",
  },
  {
    name: "Burguer Kenzie",
    img: "https://i.imgur.com/GwDPeQJ.png",
    desc: "A Burguer Kenzie é uma pequena hamburgueria virtual, onde é possível adicionar e remover produtos do carrinho e vizualizar o preço total dos produtos, além de ter um filtro de pesquisa robusto. Feito em React, Html, Css e JavaScript.",
    git: "https://github.com/nicollasanderson/Burguer-Kenzie",
    demo: "https://react-entrega-s1-hamburgueria-da-kenzie-nicollasanderson.vercel.app/",
    stack: "Front-end",
  },
  {
    name: "G4mes Hub",
    img: "https://i.imgur.com/wBett4k.png",
    desc: "O G4mes Hub é uma plataforma de interação entre jogadores de todo o mundo. Aqui, você pode deixar sua opinião sobre diversos jogos, além de deixar seu link e uma pontuação. Projeto em grupo feito no final do 3° módulo de React.",
    git: "https://github.com/victor-sagulo/capstone-m3-projeto-final",
    demo: "https://capstone-m3-projeto-final.vercel.app/",
    stack: "Front-end",
  },
  {
    name: "Music Club Shop API",
    img: "https://i.imgur.com/gKNHmfF.png",
    desc: "API Restful feita com o objetivo de gerenciar uma loja de instrumentos e materiais musicais. Usuários podem se cadastrar, adicionar produtos ao carrinho e enviar para o endereço desejado. Projeto em grupo feito com Node.js, Typescript e Postgresql para o capstone do 4° módulo da Kenzie Academy Brasil.",
    git: "https://github.com/nicollasanderson/music-club-shop-api",
    demo: "https://api-music-club-shop.herokuapp.com/",
    stack: "Back-end",
  },
  {
    name: "Empresa Python",
    img: "https://www.digitalhouse.com/br/blog/content/images/size/w2000/2022/05/DH_blog_thumb_11.05.jpg",
    desc: "Sistema simples de gerenciamento de uma empresa, onde é possível criar uma empresa, funcionários e genrentes e associar elas entre si, além de salvar a empresa em um arquivo json. Projeto feito com o objetivo de aprender as bases de Python para realizar a criação de API's Restful.",
    git: "https://github.com/nicollasanderson/Empresa-Python",
    demo: "#",
    stack: "Back-end",
  },
  {
    name: "Kenzie Pet",
    img: "https://www.digitalhouse.com/br/blog/content/images/size/w2000/2022/05/DH_blog_thumb_11.05.jpg",
    desc: "API Restful simples para cadastrar animais, suas espécies e características. Projeto feito com Python, Django e Rest Framework.",
    git: "https://github.com/nicollasanderson/Kenzie-Pet",
    demo: "#",
    stack: "Back-end",
  },
];
